server {
    listen 80;
    server_name _;

    location /holokit/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /holokit/index.html;
    }

    location /holokit {
        return 301 /holokit/;
    }
}
