export { InteractionManager } from './InteractionManager'
export type { InteractionEvent, InteractionHandler } from './InteractionManager'
export { Tooltip } from './Tooltip'
export type { TooltipOptions } from './Tooltip'
export { Legend } from './Legend'
export type { LegendItem, LegendOptions } from './Legend'
